mex -R2018a ...
    -I"C:\Program Files (x86)\DACE\include" ...
    -I"C:\msys64\mingw64\include" ...
    -I"C:\Users\mbudd\Documents\thesis\eigen-3.4.0" ...
    -L"C:\Program Files (x86)\DACE\lib" ...
    -L"C:\msys64\mingw64\lib" ...
    -L"C:\Program Files\MATLAB\R2022a\bin\win64" ...
    cpp/CloudProp.cpp ...
    -ldace ...
    COMPFLAGS="$COMPFLAGS /utf-8"